// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIEFP-I7KxPFwmSYvwoN-eDci2cN8JUu8',
    appId: '1:210005321268:web:ba9152af4d68814f658c61',
    messagingSenderId: '210005321268',
    projectId: 'fir-practice-753ee',
    authDomain: 'fir-practice-753ee.firebaseapp.com',
    storageBucket: 'fir-practice-753ee.firebasestorage.app',
    measurementId: 'G-58GRS6KFVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJv_vtcRhzI8o8vp0CHTlVhsyMqZVWmeM',
    appId: '1:210005321268:android:0fb5f8d7ff9c75d3658c61',
    messagingSenderId: '210005321268',
    projectId: 'fir-practice-753ee',
    storageBucket: 'fir-practice-753ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo6pVkZIx-UfrfNKxhekJvyqJf2ZnSIp0',
    appId: '1:210005321268:ios:86d7ae002dd47810658c61',
    messagingSenderId: '210005321268',
    projectId: 'fir-practice-753ee',
    storageBucket: 'fir-practice-753ee.firebasestorage.app',
    iosBundleId: 'com.example.ciCdExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo6pVkZIx-UfrfNKxhekJvyqJf2ZnSIp0',
    appId: '1:210005321268:ios:86d7ae002dd47810658c61',
    messagingSenderId: '210005321268',
    projectId: 'fir-practice-753ee',
    storageBucket: 'fir-practice-753ee.firebasestorage.app',
    iosBundleId: 'com.example.ciCdExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIEFP-I7KxPFwmSYvwoN-eDci2cN8JUu8',
    appId: '1:210005321268:web:5d99d828816bbada658c61',
    messagingSenderId: '210005321268',
    projectId: 'fir-practice-753ee',
    authDomain: 'fir-practice-753ee.firebaseapp.com',
    storageBucket: 'fir-practice-753ee.firebasestorage.app',
    measurementId: 'G-KBYPS3J5QL',
  );
}
