# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  lane :playstore do
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )
end

  desc "My awesome app"
    lane :distribute do
        # build_android_app is a built-in fastlane action.
        release = firebase_app_distribution(
            app: "1:210005321268:android:7eca692c641cce5f658c61",
            testers: "vishnukhandelwal1001@gmail.com, vishnu.khandelwal@mediologysoftware.com",
            android_artifact_type: "APK",
            android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
            release_notes: ENV["RELEASE_NOTES"] || "Lots of amazing new features to test out!"
        )
    end

  desc "Deploy a new version to the Google Play internal track"
  lane :deploy do
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      release_status: 'completed',
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
  
end
