# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  lane :playstore do
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )
end

  desc "My awesome app"
    lane :distribute do
        # build_android_app is a built-in fastlane action.
        release = firebase_app_distribution(
            app: "1:210005321268:android:0fb5f8d7ff9c75d3658c61",
            testers: "vishnukhandelwal1001@gmail.com, vishnu.khandelwal@mediologysoftware.com",
            android_artifact_type: "APK",
            android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
            release_notes: "Lots of amazing new features to test out!"
        )
    end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
  
end
